# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='laboratorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.IntegerField()),
                ('dia', models.IntegerField()),
                ('hora', models.IntegerField()),
                ('libre', models.BooleanField()),
            ],
        ),
    ]
