# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorio',
            name='clases',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
